http:
  port: 8090
apiEndpoints:
  addSong:
    paths:
      - "/song/add"
  user:
    paths:
      - "/user/*"
  admin:
    paths:
      - "/admin/*"
  auth:
    paths:
      - "/auth/*"
serviceEndpoints:
  userService:
    url: "http://127.0.0.1:3002"
  userCustom:
    url: "http://127.0.0.1:3002/user"
  adminService:
    url: "http://127.0.0.1:3001"
  authService:
    url: "http://127.0.0.1:3003"
policies:
  - proxy
  - cors
  - jwt
  - verify-token
  - verifyArtist-token
  - verifyAdmin-token
pipelines:
  addSong:
    apiEndpoints:
      - addSong
    policies:
      - verifyAdmin-token:
      - cors:
      - proxy:
          - action:
              serviceEndpoint: userService
  auth:
    apiEndpoints:
      - auth
    policies:
      - cors:
      - proxy:
          - action:
              serviceEndpoint: authService
  user:
    apiEndpoints:
      - user
    policies:
      - verify-token:
      - proxy:
          - action:
              serviceEndpoint: userService
              prependPath: true
              ignorePath: false
              stripPath: true
  admin:
    apiEndpoints:
      - admin
    policies:
      - proxy:
          - action:
              serviceEndpoint: adminService
              prependPath: true
              ignorePath: false
              stripPath: true
