http:
  port: 8090
apiEndpoints:
  user:
    paths:
      - "/user/*"
  admin:
    paths:
      - "/admin/*"
  auth:
    paths:
      - "/auth/*"
serviceEndpoints:
  userService:
    url: "http://127.0.0.1:3002"
  adminService:
    url: "http://127.0.0.1:3001"
  authService:
    url: "http://127.0.0.1:3003"
policies:
  - proxy
  - cors
  - jwt
pipelines:
  auth:
    apiEndpoints:
      - auth
    policies:
      - cors:
      - proxy:
          - action:
              serviceEndpoint: authService
  user:
    apiEndpoints:
      - user
    policies:
      - jwt:
          - action:
              secretOrPublicKey: dat dep trai
              checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: userService
              prependPath: true
              ignorePath: false
              stripPath: true

  admin:
    apiEndpoints:
      - admin
    policies:
      - jwt:
          - action:
              secretOrPublicKey: dat dep trai
              checkCredentialExistence: true
      - proxy:
          - action:
              serviceEndpoint: adminService
              prependPath: true
              ignorePath: false
              stripPath: true
