http:
  port: 8090
apiEndpoints:
  countFollow:
    paths:
      - "/follow/:followId"
  getSong:
    paths:
      - "/song"
  getTypeSong:
    paths:
      - "/typeSong"
  getSongFollowArtist:
    paths:
      - "/song/artist/*"
  getUserTypeNormal:
    paths:
      - "/user/typeAccount/:typeAccountId"
  getArtist:
    paths:
      - "/user/getArtist"
  getSongVietNam:
    paths:
      - "/song/vietnam"
  getSongOtherCountry:
    paths:
      - "/song/otherCountry"
  addSong:
    paths:
      - "/song/add"
  user:
    paths:
      - "/user/*"
  admin:
    paths:
      - "/admin/*"
  auth:
    paths:
      - "/auth/*"
serviceEndpoints:
  userService:
    url: "http://127.0.0.1:3002"
  adminService:
    url: "http://127.0.0.1:3001"
  authService:
    url: "http://127.0.0.1:3003"
policies:
  - proxy
  - cors
  - verify-token
  - verifyArtist-token
  - verifyAdmin-token
pipelines:
  getUserTypeNormal:
    apiEndpoints:
      - getUserTypeNormal
    policies:
      - cors:
          - action:
              origin: "http://127.0.0.1:5501"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: adminService
  getSong:
    apiEndpoints:
      - getSong
    policies:
      - cors:
          - action:
              origin: "http://127.0.0.1:5501"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: userService
  countFollow:
    apiEndpoints:
      - countFollow
    policies:
      - cors:
          - action:
              origin: "http://127.0.0.1:5501"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: userService
  getTypeSong:
    apiEndpoints:
      - getTypeSong
    policies:
      - cors:
          - action:
              origin: "http://127.0.0.1:5501"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: userService
  getSongFollowArtist:
    apiEndpoints:
      - getSongFollowArtist
    policies:
      - cors:
          - action:
              origin: "http://127.0.0.1:5501"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: userService
  getArtist:
    apiEndpoints:
      - getArtist
    policies:
      - cors:
          - action:
              origin: "http://127.0.0.1:5501"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: userService
  getSongVietNam:
    apiEndpoints:
      - getSongVietNam
    policies:
      - cors:
          - action:
              origin: "http://127.0.0.1:5501"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: userService
  getSongOtherCountry:
    apiEndpoints:
      - getSongOtherCountry
    policies:
      - cors:
          - action:
              origin: "http://127.0.0.1:5501"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: userService
  addSong:
    apiEndpoints:
      - addSong
    policies:
      - verifyAdmin-token:
      - cors:
          - action:
              origin: "http://127.0.0.1:5501"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: userService
  auth:
    apiEndpoints:
      - auth
    policies:
      - cors:
          - action:
              origin: "http://127.0.0.1:5501"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: authService
  user:
    apiEndpoints:
      - user
    policies:
      - cors:
          - action:
              origin: "http://127.0.0.1:5501"
              methods: "HEAD,PUT,PATCH,POST,DELETE"
              credentials: true
      - verify-token:
      - proxy:
          - action:
              serviceEndpoint: userService
              prependPath: true
              ignorePath: false
              stripPath: true
  admin:
    apiEndpoints:
      - admin
    policies:
      - cors:
      - verifyAdmin-token:
      - proxy:
          - action:
              serviceEndpoint: adminService
              prependPath: true
              ignorePath: false
              stripPath: true
