# Core
db:
  redis:
    emulate: true
    namespace: EG

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
  # secretOrPrivateKey: "dat dep trai"
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
plugins:
  my-policy:
    package: "../../../plugins/my-plugin/manifest.js"
  verifyArtist-token:
    package: "../../../plugins/verifyArtist-token/manifest.js"
  verifyAdmin-token:
    package: "../../../plugins/verifyAdmin-token/manifest.js"
